### PR TITLE
Viewer upgrade

### PR DESCRIPTION
**Pull request by Titwin**
- Add picking,
- Add Thymio 3D model,
- Add Thymio texturing and leds support,
- ...

### CODE REVIEW

**Comment by davidjsherman** [comment]
I have broken this PR into five pieces. I will submit them as PRs to [Titwin/enki-INRIA](https://github.com/Titwin/enki-INRIA) so that @Titwin can make his own branches from them and submit the corresponding PRs. (I won't be working on these any further!) All of this code is @Titwin's, I only made minor changes to allow the pieces to compile independently, to avoid some warnings, and to fix formatting.

* https://github.com/enki-community/enki/compare/master...davidjsherman:pr17-preparation <br/>Some cleanup to compile on all platforms
 * https://github.com/davidjsherman/enki/compare/pr17-preparation...davidjsherman:pr17-picking <br/>Picking mechanism added to the viewer
   * https://github.com/davidjsherman/enki/compare/pr17-picking...davidjsherman:pr17-playground <br/>Update the **enkiplayground** GUI to use the picking mechanism
 * https://github.com/davidjsherman/enki/compare/pr17-preparation...davidjsherman:pr17-textures <br/>Improved textures from the photos taken by Vincent Becker

Each one of these branches [compiles on the three platforms](https://ci.inria.fr/inirobot/job/Enki-djs/). I was not able to use the new textures in **asebaplayground**, because it locally implements a lot of the rendering that should be in Enki. The code does compile, though.

Since the final merge of [pr17-playground](https://github.com/davidjsherman/enki/tree/pr17-playground) with [pr17-textures](https://github.com/davidjsherman/enki/tree/pr17-textures) involves a tiny conflict that was easier to resolve by hand, I also made a merge branch as a final check.

* https://github.com/enki-community/enki/compare/master...davidjsherman:pr17-merge

**Comment by davidjsherman** [comment]
Actually it doesn't make sense for me to submit them as PRs, the base commit is aea85abed9517501615624baaa631d91da59952f not a branch in [Titwin/enki-INRIA](https://github.com/Titwin/enki-INRIA). @Titwin, can you just pull my branches into your fork?
```
git remote add djs git://github.com/davidjsherman/enki.git
git fetch djs
git checkout --track djs/pr17-preparation
git checkout --track djs/pr17-picking
git checkout --track djs/pr17-playground
git checkout --track djs/pr17-textures
```

Then submit PRs as usual.

**Comment by Titwin** [comment]
Done :
I import your branches and pull them in my github account as new branches,
and then I created pull request for Stephane.
Do I need to wait that the 'Pr17 preparation' is accepted before to send the others PR ?

**Comment by davidjsherman** [comment]
I would submit them all, the dependencies are clearly shown in https://github.com/Titwin/enki-INRIA/network. That way they can all be discussed independently. The only real dependency is in  [pr17-picking](https://github.com/Titwin/enki-INRIA/tree/pr17-picking) (6ab205ffbf6345db8945237b31758ec4289d5906): if there are significant changes to its API then [pr17-playground](https://github.com/Titwin/enki-INRIA/tree/pr17-playground) (717c8af608a49b1d80cc5ee80cbec3d4fd224e41) will have to be changed.

Theoretically, if the mechanism in [pr17-picking](https://github.com/Titwin/enki-INRIA/tree/pr17-picking) works, then [asebaplayground](https://github.com/aseba-community/aseba/tree/master/targets/playground) could be minimally changed to add picking to the current simulation while maintaining the old GUI and rendering.

**Comment by stephanemagnenat** [comment]
> Theoretically, if the mechanism in pr17-picking works, then asebaplayground could be minimally changed to add picking to the current simulation while maintaining the old GUI and rendering.

Indeed, I would like to merge picking as soon as possible, while the rest in not as urgent. One of the reason is that in parallel, as part of a EU project, there is another Enki re-factoring going on.

**Comment by davidjsherman** [comment]
Asebaplayground will compile with pr17-picking if you comment out `PlaygroundViewer::setCamera`, which incorrectly overrides `ViewerWidget::setCamera`.

**Comment by stephanemagnenat** [comment]
Outdated, removing.

**Pull request closed without merging**
