### PR TITLE
Pr17 textures

### PR DESCRIPTION
**Pull request by Titwin**
Add texture for Thymio robot

### CODE REVIEW

**Comment by stephanemagnenat** [comment]
@Titwin, could you please rebase this PR on Enki master? Thank you!

**Comment by Titwin** [comment]
Done

**Comment by stephanemagnenat** [comment]
Beside the question of the saturation of the LEDs in the texture space, I'm happy with this PR and ready to merge. @davidjsherman are you available to shortly discuss about the texture creation process?

**Comment by stephanemagnenat** [comment]
I've started merging on my side, the conflict is very tiny and easy to correct by hand.

One thing I do not understand is why there are these two members in `enki/robots/thymio2/Thymio2.h`: `unsigned int textureID` and `unsigned int* ledTexture`? Did you forget to remove them when you moved the texture code into `viewer/Thymio2Model.h`?

**Comment by stephanemagnenat** [comment]
@Titwin , ok for you to close this PR?

**Comment by Titwin** [comment]
Ok 

----- Mail original -----

**Pull request closed without merging**
